### ISSUE TITLE
No matching distribution found for TTS==0.21

### ISSUE THREAD

**Issue by elfgoose** [BoltzmannEntropy/xtts2-ui#24]
Hey,

My installation is failing at the requirements.txt stage.: 
ERROR: Could not find a version that satisfies the requirement TTS==0.21.* (from versions: none)
ERROR: No matching distribution found for TTS==0.21.*

Any help would be appreciated

Thnaks

**Comment by BoltzmannEntropy** [comment]
OS? Python version?

**Comment by tajnymag** [comment]
Not op, but the same happens to me on Windows 11 x64, python 3.12.2.

**Comment by Th3Rom3** [comment]
Requirements install fine on a Python 3.11.8 environment. So you could try either downgrading the python version in the venv or adjust the packages manually (if equivalents exist for Python 3.12).

**Comment by EmersonBiggons** [comment]
when you first start the python venv, use the below command instead. Make sure to delete your venv folder before doing this.
`python3.10 -m venv venv`
Py 3.12 isnt supported by xTTS and since the project is depricated you have to use an older version of python. Which fine since the only difference is one command and redownloading stuff.
